[mypy]
python_version = 3.11
ignore_missing_imports = True
explicit_package_bases = True
disable_error_code = import-untyped

[mypy-packages.pipeline_core.e4_media_pipeline]
disable_error_code = name-defined
